require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods'

platform :ios, '10.0'

target 'hexa' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-randombytes', :path => '../node_modules/react-native-randombytes'
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'
  pod 'RNFirebase/Crashlytics', :path => '../node_modules/react-native-firebase/ios'

  pod 'Firebase/Core', '~> 6.13.0'
  pod 'Firebase/Messaging', '~> 6.13.0'
  pod 'GoogleIDFASupport', '~> 3.14.0'

  pod 'Fabric'
  pod 'Crashlytics'
  pod 'PDFGenerator'
  pod 'QRCoder'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  target 'hexaTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'hexa-tvOS' do
  # Pods for hexa-tvOS

  target 'hexa-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
